version: '3'
services:
  python:
    container_name: python
    build:
      context: ./
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - .:/project
    ports:
      - "8888:8888"